name: Sync Upstream
on:
  schedule:
    - cron: '0 * * * *' # 每小时检查一次
  workflow_dispatch:    # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Sync from Upstream
        run: |
          # 1. 设置原作者仓库为 upstream
          git remote add upstream https://github.com/akfamily/akshare.git
          # 2. 拉取原作者代码
          git fetch upstream
          # 3. 切换到你的 main 分支
          git checkout main
          # 4. 合并原作者的 main 分支到你的分支
          git merge upstream/main
          # 5. 推送回你自己的 GitHub 仓库
          git push origin main
